export { default as Dashboard } from './Admin/Dashboard'
export { default as Footer } from './Footer'
export { default as Navbar} from './Navbar'
export { default as HomePage } from './HomePage'
export { default as ChatBoard} from './ChatBoard'
export { default as Design} from './Admin/Design'
export { default as SideBar} from './Sidebar'